import type { Metadata } from "next";
import { Inter } from "next/font/google";
//import 'https://fonts.cdnfonts.com/css/space-age'

import "./globals.css";
// import "./assets/Age.otf"
const inter = Inter({ subsets: ["latin"] });
console.log(inter, "inter");
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  );
}
